accounts/abi/bind: allow to specify signer on transactOpts
ethereum/go-ethereum pull request #21356
Opened 2020-07-22 09:34 UTC by MariusVanDerWijden

This commit enables users to specify which signer they want to use while creating their transactOpts.
Previously all contract interactions used the homestead signer. Now a user can specify whether they
want to sign with homestead or EIP155 and specify the chainID which adds another layer of security.

closes https://github.com/ethereum/go-ethereum/issues/16484

2020-07-24 07:07 UTC, karalabe commented
Wondering if we should use a `chainid` instead of a signer as a new parameter? The `auth` package is mostly a convenience thing so you don't need to construct your transactor manually and so you don't need to care about the details. It seems sane to me to explicitly enforce EIP155 in a convenience method and let the user do the manual dance if they want he unsecure version. It's also easier to tell the users to pass the chainid, than to "construct an EIP155 signer".

What are your thoughts? I'm open to alternatives, just looking at it from an API perspective.

Also this PR would break all existing code relying on abigen generated contracts :P

2020-07-24 07:34 UTC, MariusVanDerWijden commented
Yeah I think that might be a better interface, we don't really want to encourage homestead signers anymore, right?
I'll change it to use ChainID and eip155 signers. 
About breaking all existing contracts: Yeah but I think the change might be so useful that it outweighs the inconveniences.
Only problem I can see is that Dapp developers have to introduce a global variable to identify the network, default it to 1 and set it to 1337 in testing. Oh btw It is not really documented that all simulated backends run chains with chainID 1337 in the source code, shall I add some docu there?

2020-07-24 07:37 UTC, karalabe commented
The more docs the better :)

2020-09-01 10:27 UTC, holiman approved these changes
Makes sense to me, but I'm not really well versed in that whole abi/bind thingy, I've never used it and am not the best person to give a thumbs-up :)

2020-09-01 10:54 UTC, gballet requested changes
In order not to break contracts right off the bat, It should be possible to keep the legacy system and display a deprecation warning when the function is used, and offer the new API with a slightly different name. Leave it like that for a few releases and then remove it.

2020-09-01 18:11 UTC, MariusVanDerWijden commented
Hmm I restored the old functions now, I'm not a huge fan, but at least I'll get a purely red pr in some months

2020-09-07 13:25 UTC, gballet approved these changes
LGTM

2020-09-29 08:39 UTC, karalabe commented on accounts/abi/bind/auth.go
> +		// If no chainID is explicitly passed, sign for mainnet
I don't think this is a good idea, you definitely don't want to accidentally default to the most dangerous network.

2020-09-29 08:39 UTC, karalabe commented on accounts/abi/bind/auth.go
> +		// If no chainID is explicitly passed, sign for mainnet
IMHO we should return an error. If you call `WithCHainID` **wihut** it, it's much rather a bug than an omission

2020-11-04 09:28 UTC, MariusVanDerWijden commented
cc @fjl

2020-12-04 13:06 UTC, MariusVanDerWijden commented
cc @fjl

2020-12-08 10:21 UTC, fjl approved these changes

2020-12-08 10:22 UTC, MariusVanDerWijden commented on accounts/abi/bind/auth.go
> +var NoChainID = errors.New("no chain id specified")
ErrNoChainID

2020-12-08 10:22 UTC, fjl requested changes
See you in 40 days!

2020-12-08 10:22 UTC, fjl commented on accounts/abi/bind/auth.go
> +var NotAuthorized = errors.New("not authorized to sign this account")
NotAuthorized -> ErrNotAuthorized

2020-12-08 13:44 UTC, merged