accout,core,eth,les,miner: replace unused RWMutex
ethereum/go-ethereum pull request #21622
Opened 2020-09-25 07:08 UTC by mrFranklin

These RWMutex are not use `RLock()`, they are only use `Lock()`, so replace them with `Mutex`

2020-09-29 11:59 UTC, MariusVanDerWijden requested changes
The linter is red, please fix

2020-09-29 11:59 UTC, MariusVanDerWijden commented on eth/helper_test.go
> -	lock sync.RWMutex // Protects the transaction pool
Revert this change, Pending uses RLock

2020-09-29 13:56 UTC, mrFranklin commented on eth/helper_test.go
> -	lock sync.RWMutex // Protects the transaction pool
My fault. 
fixed.

2020-10-13 08:57 UTC, holiman approved these changes

2020-10-13 08:58 UTC, MariusVanDerWijden approved these changes

2020-10-13 08:58 UTC, merged