eth: add a method to eth to return chainID from config, regardless of sync status
ethereum/go-ethereum pull request #21686
Opened 2020-10-11 20:41 UTC by renaynay

This PR adds a method to the public eth api to return the `chainID` regardless of sync status. 

Sync status is required by the `chainId()` method in order to return the proper chainID, due to the following condition: 

```go
config.IsEIP155(api.e.blockchain.CurrentBlock().Number())
```

2020-10-12 13:10 UTC, holiman approved these changes
LGTM. But I can't say I fully understand why it was implemented like this in the first place, I assume there's some reason for it...

2020-10-12 13:38 UTC, renaynay commented
@holiman #17617 added the chainID method, with the EIP155 check. I found some discussion about it here: https://github.com/ethereum/go-ethereum/pull/15002, where you ask a similar question here: https://github.com/ethereum/go-ethereum/pull/15002#pullrequestreview-65513361

to which the response is https://github.com/ethereum/go-ethereum/pull/15002#issuecomment-332497617

Could this change conflict with what's described in EIP695: https://github.com/ethereum/EIPs/pull/695/files ? 

```
## Rationale
 An ETH/ETC client can accidentally connect to an ETC/ETH RPC
 endpoint without knowing it unless it tries to sign a transaction or
 it fetch a transaction that is known to have signed with a chain
 ID. This has since caused trouble for application developers, such as
 MetaMask, to add multi-chain support.
```

2020-11-10 10:30 UTC, renaynay commented
Reached out to the nucypher team, asking why they're running into this issue (#20894) so we can get some more information about why this PR is necessary.

cc @tuxxy

2020-11-12 06:26 UTC, cygnusv commented
> Reached out to the nucypher team, asking why they're running into this issue (#20894) so we can get some more information about why this PR is necessary.
> 
> cc @tuxxy

We run into this issue because as part of our logic, nucypher nodes check the `chain_id` of their ETH provider. Our testnet currently runs on Rinkeby (`chain_id=4`), but we've detected some situations where the ETH node incorrectly states it's running `chain_id=0` (see https://github.com/nucypher/nucypher/issues/2295). This can cause some problems in our end (nothing too worrisome), but the issue here IMHO is that the user expects that the output of the chain_id endpoint it's not going to be contingent on the sync status.

2020-11-24 03:08 UTC, PatrickAlphaC commented
Would like to get this in. It _looks_ like my mainnet node is synced, but it's still returning `0x0` for `chainId`:

curl http://127.0.0.1:8545 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "method":"eth_chainId","params": [], "id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x0"}

This won't let my beacon chain start. 
Version: 1.9.24-stable-cc05b050

2020-11-25 00:26 UTC, prestonvanloon commented
Hi! Is there any update on this? 

We are having a bit of pain with ETH2 setup. Users are reporting their go-ethereum nodes returning a 0 chain ID. The correct chain ID is a hard requirement for prysm. 

Thank you!! :pray:

2020-11-25 01:26 UTC, egk10 commented
is 1 block delay consider UNSYNC ?? see printscreen ETHERSCAN vs GETH --HTTP

![sync](https://user-images.githubusercontent.com/69823897/100170218-eb782a80-2ea3-11eb-8a74-d43c2d2a163e.PNG)


[2020-11-24 22:23:09] ERROR powchain: Could not connect to powchain endpoint error=eth1 node using incorrect chain id, 0 != 1
could not dial eth1 nodes
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).connectToPowChain
        beacon-chain/powchain/service.go:358
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).waitForConnection
        beacon-chain/powchain/service.go:445
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1
        beacon-chain/powchain/service.go:249
runtime.goexit
        src/runtime/asm_amd64.s:1374
![sync](https://user-images.githubusercontent.com/69823897/100170184-d8655a80-2ea3-11eb-9bd3-4c3bb381e059.PNG)

2020-11-25 01:32 UTC, PatrickAlphaC commented
> Hi! Is there any update on this?
> 
> We are having a bit of pain with ETH2 setup. Users are reporting their go-ethereum nodes returning a 0 chain ID. The correct chain ID is a hard requirement for prysm.
> 
> Thank you!! 🙏

So I found out that if your ETH 1 node is returning 0, it means it's not fully synced. So the users still need to wait for it to fully sync up before moving forward. That being said, more clear logging is for sure needed, but this shouldn't be a stopper for anyone going ETH 2.

2020-11-25 07:28 UTC, rjl493456442 commented on eth/api.go
> +	chainID = api.e.blockchain.Config().ChainID
We can simplify it to `return (hexutil.Uint64)(api.e.blockchain.Config().ChainID.Uint64())`

2020-11-25 07:29 UTC, rjl493456442 approved these changes
Just nitpicks, lgtm

2020-11-25 07:31 UTC, karalabe commented
@prestonvanloon @egk10 Geth returns the chain ID that's relevant at the block it's at. If you haven't synced up, you only have the genesis block available, which does not have a chain id. The screenshot attached is clearly not synced yet, so the only full block it has is the genesis. Please check `eth.blockNumber` or `eth.getBlock('latest')` to figure out if you're in sync or not. Don't even bother trying to use a node that's not synced.

2020-12-08 10:02 UTC, holiman commented
The problem on prysmatic labs side fixed here: https://github.com/prysmaticlabs/prysm/pull/7895 .

2020-12-08 10:09 UTC, fjl commented
In [EIP-695](https://eips.ethereum.org/EIPS/eip-695), it says

> The chain ID returned should always correspond to the information in the current known head block. This ensures that caller of this RPC method can always use the retrieved information to sign transactions built on top of the head.

> If the current known head block does not specify a chain ID, the client should treat any calls to eth_chainId as though the method were not supported, and return a suitable error.

So, the current geth behavior and this PR are not correct. eth_chainId should return an error when the current block is not EIP155-enabled.

2020-12-08 10:13 UTC, fjl requested changes

2020-12-08 10:13 UTC, fjl commented on eth/api.go
> +	return api.e.blockchain.Config().IsEIP155(api.e.blockchain.CurrentBlock().Number())
Please remove this method

2020-12-08 10:13 UTC, fjl commented on eth/api.go
> +	return (hexutil.Uint64)(api.e.blockchain.Config().ChainID.Uint64())
Let's return an error when the current block does not have EIP-155 yet.

2020-12-08 12:18 UTC, cygnusv commented
@renaynay Thanks for being on top of this! The current state of the PR, throwing an error when we're below the EIP-155 block, seems like the right approach.

2021-01-12 09:48 UTC, fjl approved these changes

2021-01-12 09:52 UTC, merged