cmd,core,eth,params,tests: enable 2565 for yolov3
ethereum/go-ethereum pull request #22213
Opened 2021-01-22 12:23 UTC by s1na

There were a few things that I _think_ can only be done later, like setting bootnodes, genesis data, etc. In those cases I only renamed the variable but didn't touch the values.

Also the bls_fuzzer depended on those precompiles being exported so I created another set just for that.

I'm planning to tinker around with this a bit more make sure I haven't left anything out.

2021-01-22 15:14 UTC, holiman commented
Haven't reviewed in-depth, but it looks more or less like what I had expected :+1:

2021-01-22 16:16 UTC, s1na commented
It seems like some blockchain and state tests are failing because the Berlin tests are not based on YoloV3. When I add the BLS precompiles and unset the modexp flag they pass.

2021-01-25 11:56 UTC, holiman commented
> It seems like some blockchain and state tests are failing because the Berlin tests are not based on YoloV3. 

Yes, that makes sense. It's one reason why I tried to get everyone to implemenet `YOLOv1`, `YOLOv2` etc, instead of aliasing it as `Berlin`, because we'd wind up in exactly this scenario where we mismatch of the definitions. 

Rant aside, we'll just have to skip these tests, which can be done in `tests/block_test.go` and `tests/state_test.go`

2021-01-25 12:08 UTC, holiman commented on cmd/utils/flags.go
> +			cfg.NetworkId = 133519467574834 // "yolov3"
I also made this mistake when updating `yolov1` to `yolov2`. But actually: 
```
>>> import codecs
>>> codecs.decode(hex(133519467574834)[2:], "hex")
b'yolov2'
```
So this should be changed from `133519467574834` to `133519467574835`

2021-01-25 12:08 UTC, holiman commented on cmd/utils/flags.go
> +			cfg.NetworkId = 133519467574834 // "yolov3"
Or, even better, you can fix it so we don't do the same mistake again, and change it t
```
new(big.Int).SetBytes([]byte("yolov3")).Uint64()
```

2021-01-27 15:21 UTC, holiman commented on params/bootnodes.go
> +// TODO: Set Yolov3 bootnodes
I think we can leave this as is, and reuse both nodekey and IP.

2021-01-27 15:24 UTC, holiman requested changes
I think this is OK. The problem is that unless we also merge 2718/2930, we don't have a correct yolov3. So maybe we should disable `--yolov3` here (just comment out the flag), and then un-comment it in 2718/2930. 
That would make it possible to merge this, and then rebase 2718, and run yolov3 from that PR without 
1. merging that PR to master, and 
2. Having a confusing misconfigured `--yolov3` mode on `master`

2021-01-27 15:31 UTC, holiman approved these changes
Ok, I disabled the `--yolov3` switch now, so I think this is good to go. 
@karalabe PTAL?

2021-01-28 20:19 UTC, merged