Dockerfile: added Dockerfile for arm64 compilation
ethereum/go-ethereum pull request #22477
Opened 2021-03-10 21:01 UTC by Kr0n0

Added new Dockerfile for ARM64 docker build :

- Builder Image : GOARCH parameter for ARM64 binary build.
- Deploy Image : arm64v8/alpine instead of default

Tested on nVidia Jetson Nano cluster boards

2021-03-11 11:46 UTC, holiman approved these changes
LGTM

2021-03-12 11:17 UTC, karalabe commented
If we're going to do this (not sure yet), we'll need to keep it symmetric with the current Dockerfiles too. Please add the `alltools` file too for arm.

2021-03-14 15:14 UTC, karalabe requested changes
See above

2021-03-15 19:39 UTC, jclapis commented
I'll add a +1 for this, I'm helping Rocket Pool add support for ARM64 and they use a docker-based setup for installation so this would be very helpful. Having to maintain our own docker images is not ideal. Would these images be added to the CD pipeline and deployed to Docker Hub?

2021-03-15 23:34 UTC, Kr0n0 commented
Added new alltools Dockerfile for ARM64 docker build as requested.

2021-03-16 09:28 UTC, karalabe commented
Did you actually run this successfully?

2021-03-16 09:40 UTC, karalabe commented
Soo, we'r a bit confused about this PR. 

First, both the golang builder image and the alpine deployer image have arm64 version on docker hub, so building the original Dockerfile on an ARM system should work out of the box. Why did you need to explicitly change anything in it? Why the need for the ARMv8 env var (since it will be the default on Arm systems) and why change from the official alpine image to another org in the last step (since docker hub says the original also has armv8 builds available)?

I..e Don't the original dockerfiles "just work" on ARM64 as is wrt building locally?

---

If it's about building arm64 images on an amd64 CPU to cross compile (e.g. on docker hub), then that doesn't work and would need some tweaking.

Unsure all in all where you're going, pleas provide some more infos.

2021-03-16 13:30 UTC, jclapis commented
> Soo, we'r a bit confused about this PR.
> 
> First, both the golang builder image and the alpine deployer image have arm64 version on docker hub, so building the original Dockerfile on an ARM system should work out of the box. Why did you need to explicitly change anything in it? Why the need for the ARMv8 env var (since it will be the default on Arm systems) and why change from the official alpine image to another org in the last step (since docker hub says the original also has armv8 builds available)?
> 
> I..e Don't the original dockerfiles "just work" on ARM64 as is wrt building locally?

I can confirm that the original Dockerfile currently in the repo works as-is for building on ARM if you're already on ARM (e.g. a Raspberry Pi). That's how we do it now.

2021-03-16 15:56 UTC, karalabe commented
Ok, given the above, I think it's safe to close this PR. You can build the docker image locally on an arm system.

Wrt docker hub, they don't support arm64 builders for now and hacking in a cross compilation to do automated builds will get messy fast. I'm not a fan of extending our CI infra with arm cross compilation and direct image uploads to docker hub.

2021-03-17 08:29 UTC, closed without merging