docs: update docs to v1.10.7 CLI commands
ethereum/go-ethereum pull request #23390
Opened 2021-08-12 17:15 UTC by Zachinquarantine

2021-08-13 07:42 UTC, karalabe requested changes
You need to get rid of all the spurious whitespaces. Perhaps check your editor, seems you have some auto-indentation in place that makes things go weird.

2021-08-20 06:32 UTC, MariusVanDerWijden approved these changes
LGTM, just a tiny nitpick

2021-08-20 06:32 UTC, MariusVanDerWijden commented on docs/_interface/Command-Line-Options.md
> -   Copyright 2013-2021 The go-ethereum Authors
Please don't delete this tab

2021-08-23 23:41 UTC, Zachinquarantine commented
closing this because v1.10.8 is coming out very soon and I'll send a PR for the docs then instead...

2021-08-23 23:41 UTC, closed without merging