ethereum: marshal FilterQuery struct to JSON correctly
ethereum/go-ethereum pull request #23864
Opened 2021-11-07 01:09 UTC by zenovich

Marshal FilterQuery struct to JSON correctly (name fields according to the spec, encode fromBlock and toBlock as hexadecimals) so that it could be used to call JSON-RPC methods like eth_newFilter().

2021-11-09 09:21 UTC, fjl requested changes
We cannot make this change because it is an API change. This struct cannot be modified.

If we want to add JSON marshaling for this type, we need to add MarshalJSON/UnmarshalJSON methods instead. The code for these methods already exists in other places in go-ethereum. For example, package ethclient contains a function that marshals FilterQuery for use with JSON-RPC.

2021-11-10 04:59 UTC, zenovich commented
No problem, @fjl. I'll rework that.

By the way, there is a question. The Ethereum Wiki (https://eth.wiki/json-rpc/API#parameters-45) says that if 'fromBlock' is missing it is treated as 'latest' while ethclient.toFilterArg() treats FromBlock==nil as 0x0 (i.e. "earliest") (see https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L406). Which path should I take?

(If you don't mind, I suggest not to reconstruct missing optional fields on marshalling, but apply default values in UnmarshalJSON() instead. This would probably make things easier.)

Also, there is an inconsistency between ethclient.toBlockNumArg() (https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L527) and the 'rpc' package constants (https://github.com/ethereum/go-ethereum/blob/master/rpc/types.go#L60): ethclient.toBlockNumArg() treats -1 as "pending" and -2 as -2 while the rpc package treats -1 as "latest" and -2 as "pending". Not sure which one is correct.

2021-11-10 14:15 UTC, fjl commented
> By the way, there is a question. The Ethereum Wiki (https://eth.wiki/json-rpc/API#parameters-45) says that if 'fromBlock' is missing it is treated as 'latest' while ethclient.toFilterArg() treats FromBlock==nil as 0x0 (i.e. "earliest") (see https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L406). Which path should I take?

It's documented in package ethereum that `FromBlock == nil` means genesis block, so we shouldn't change it.

> Also, there is an inconsistency between ethclient.toBlockNumArg() and the 'rpc' package constants : ethclient.toBlockNumArg() treats -1 as "pending" and -2 as -2 while the rpc package treats -1 as "latest" and -2 as "pending". Not sure which one is correct.

This is unfortunate, and it's my fault. In the PR that introduced it (https://github.com/ethereum/go-ethereum/pull/21177), I suggested using -1 instead of allowing all negative numbers to mean 'pending'. I did not cross-check with package rpc at that time.

I'll think about how to fix this.

2021-11-11 02:26 UTC, zenovich commented
> > By the way, there is a question. The Ethereum Wiki (https://eth.wiki/json-rpc/API#parameters-45) says that if 'fromBlock' is missing it is treated as 'latest' while ethclient.toFilterArg() treats FromBlock==nil as 0x0 (i.e. "earliest") (see https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L406). Which path should I take?
> 
> It's documented in package ethereum that `FromBlock == nil` means genesis block, so we shouldn't change it.
> 
> > Also, there is an inconsistency between ethclient.toBlockNumArg() and the 'rpc' package constants : ethclient.toBlockNumArg() treats -1 as "pending" and -2 as -2 while the rpc package treats -1 as "latest" and -2 as "pending". Not sure which one is correct.
> 
> This is unfortunate, and it's my fault. In the PR that introduced it (#21177), I suggested using -1 instead of allowing all negative numbers to mean 'pending'. I did not cross-check with package rpc at that time.
> 
> I'll think about how to fix this.

Fixed

2022-01-08 11:32 UTC, zenovich commented
@fjl, can we merge please?

2022-01-27 10:47 UTC, fjl commented
Sorry this is taking so long. I have been reviewing this on and off between other tasks, and will change some things before we can get this in.

2022-04-09 12:33 UTC, Mitumaru approved these changes

2025-03-27 14:36 UTC, s1na commented
Thanks a lot for contributing! Given that this PR has been open for quite a while (4 years!) and the codebase has evolved significantly since then, I’m going to close this to clean things up.

If anyone is still interested in pursuing this change, please feel free to open a fresh PR against the current codebase—we’d be more than happy to revisit it!

Thanks again!

2025-03-27 14:36 UTC, closed without merging