dockerfile: enable container to be run as arbitrary UID
ethereum/go-ethereum pull request #23975
Opened 2021-11-25 14:58 UTC by mikalsande

I want to be able to run geth in a container as a non-root user since that is good practice. It looks like creating an [unprivileged application user](https://github.com/ethereum/go-ethereum/pull/22861#issuecomment-839038472) is out of the question since this breaks current Docker setups.

Trying to run as non-root with the current docker image fails.
```
$ docker run -ti --rm --user 1001:1001 ethereum/client-go:v1.10.13 --ropsten
INFO [11-25|14:41:11.846] Starting Geth on Ropsten testnet...
INFO [11-25|14:41:11.849] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-25|14:41:11.850] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Fatal: Failed to create the protocol stack: mkdir /.ethereum: permission denied
```

As far as I can tell just creating `/.ethereum` in the Dockerfile makes it possible to run geth as an arbitrary UID in Docker. I have tested syncing Ropsten with this image and as far as I can tell it works as expected. The same images runs fine as root.
```
docker build -t ethereum-dev:latest .
docker run -ti --rm --user 1001 ethereum-dev:latest --ropsten
```

If there is a need to run as a UID that exists you can either run as nobody
```
docker run -ti --rm --user 65534 ethereum-dev:latest --ropsten
```
Or create a more elaborate setup such as propsed by [Red Hat to run on OpenShift](https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html). I can create a separate PR for that if needed.

2021-11-29 20:55 UTC, holiman commented
If an existing setup uses `docker -v /foo/bar/ethereum:/.ethereum run .. `, to mount `./ethereum` to an external folder -- how does that work with this change? Will it mount the external one, or will it fail to start, or will it use the local one?

2021-11-30 09:57 UTC, mikalsande commented
Docker mounts the volume over the existing directory, and it gets the same mode and ownership as the directory has on the host machine.
```
$ mkdir -p /stuff/test
$ echo "foo" > /stuff/test/bar
$ docker run -ti --rm -v /stuff/test:/.ethereum --entrypoint /bin/ash ethereum-dev:latest
$ cat /.ethereum/bar
$ ls -la | grep ethereum
drwxrwxr-x    2 1000     1000             3 Nov 30 06:42 .ethereum
```

Thank you for your follow up. From the `geth --help` output it looks like all data except the ethash mining DAGs is kept in `$HOME/.ethereum`. I have added creation of `/.ethash` to the Dockerfile in add
tion to `/.ethereum`.

Are there other workflows that I can test to verify that this change does not break anything for existing installations or future changes?

2021-11-30 10:54 UTC, holiman commented
If it mounts the volume over the existing one, how come it didn't output `foo` when you did `cat /.ethereum/bar` ?

2021-11-30 11:05 UTC, mikalsande commented
That was a copy paste error by me, sorry about that. I have run the commands again.
```
$ mkdir -p /stuff/test
$ echo "foo" > /stuff/test/bar
$ docker run -ti --rm -v /stuff/test:/.ethereum --entrypoint /bin/ash ethereum-dev:latest
/ # cat /.ethereum/bar
foo
/ # ls -la | grep ethereum
drwxrwxr-x    2 1000     1000             3 Nov 30 06:42 .ethereum
```

2021-11-30 11:47 UTC, holiman approved these changes
Seems good to me

2021-11-30 18:22 UTC, karalabe requested changes
I don't see how this solves the problem really.

The origin error you seems to solve is if you run a container with no volume mounted. In that case, a permission denied error is indeed produced, but it doesn't make any sense to run the image like that. When you stop it, all the data will be lost, which seems kind of meaningless.

Now, if I mount a non-existing folder into the new image, it will fail with the exact same error as the current images as the real folder will be created with root perms, but the image internally will try to access it without root perms:

```
$ docker run --rm -it --user 65534 -v /tmp/lalala:/.ethereum geth-pr --goerli console
Fatal: Failed to create the protocol stack: mkdir /.ethereum/goerli: permission denied

$ docker run --rm -it --user 65534 -v /tmp/lalala:/.ethereum ethereum/client-go:v1.10.13 --goerli console
Fatal: Failed to create the protocol stack: mkdir /.ethereum/goerli: permission denied
```

If I manually create the folder first with my own user and then run the docker images, both images work properly as the permissions on the host match those in the container.

```
$ sudo rm -rf /tmp/lalala
$ mkdir /tmp/lalala

$ docker run --rm -it --user 1000 -v /tmp/lalala:/.ethereum ethereum/client-go:v1.10.13 --goerli console
[...]
Welcome to the Geth JavaScript console!

$ docker run --rm -it --user 1000 -v /tmp/lalala:/.ethereum geth-pr --goerli console
[...]
Welcome to the Geth JavaScript console!
```

There's no magic conversion between host and guest permissions. If you run the image with another user, you need to have the volumes mounted from the host with the same user permissions.

I don't see a reason to make the images runnable as a non-root user without a volume mounted. Just doesn't make much sense to me.

2021-11-30 19:55 UTC, mikalsande commented
> If I manually create the folder first with my own user and then run the docker images, both images work properly as the permissions on the host match those in the container.
> 
> ```
> $ sudo rm -rf /tmp/lalala
> $ mkdir /tmp/lalala
> 
> $ docker run --rm -it --user 1000 -v /tmp/lalala:/.ethereum ethereum/client-go:v1.10.13 --goerli console
> [...]
> Welcome to the Geth JavaScript console!
> 
> $ docker run --rm -it --user 1000 -v /tmp/lalala:/.ethereum geth-pr --goerli console
> [...]
> Welcome to the Geth JavaScript console!
> ```
> 
> There's no magic conversion between host and guest permissions. If you run the image with another user, you need to have the volumes mounted from the host with the same user permissions.
> 
> I don't see a reason to make the images runnable as a non-root user without a volume mounted. Just doesn't make much sense to me.

Yes, that is a fair point. There is no point in changing the image when we can just map in a directory that already has the same permissions as the UID we run as. I guess this PR can be closed.

What is the right place to discuss documentation changes? It could be helpful to document how to run geth as non-root such as in the README.md so that this information is more easily available. Something like
```
mkdir /Users/alice/ethereum
docker run -d --name ethereum-node -v /home/ubuntu/ethereum:/.ethereum \
           -p 8545:8545 -p 30303:30303 -u $UID \
           ethereum/client-go
```

2021-11-30 19:55 UTC, closed without merging