Add specified key length iterator
ethereum/go-ethereum pull request #24535
Opened 2022-03-14 00:11 UTC by aaronbuchwald

This PR adds a db iterator wrapper that only returns key-value pairs with a specified key length.

2022-03-14 08:28 UTC, karalabe commented on core/rawdb/accessors_snapshot.go
> +	return NewKeyLengthIterator(db.NewIterator(storageSnapshotsKey(accountHash), nil), 65)
Please replace `65` with `len(SnapshotStoragePrefix) + 2*common.HashLength`

2022-03-14 08:30 UTC, karalabe commented on core/rawdb/key_length_iterator.go
> +// with key length matching [requiredKeyLength] will be returned.
Nits, we don't use `[field]` anywhere else in the code so it feels wrong to start a new style. Also, docs get exported to a documentation site where the internal fields won't be visible, so referring to them feels off.

I'd just reformulate as:

```
// KeyLengthIterator is a wrapper for a database iterator that ensures only key-value pairs
// with a specific key length will be returned.
```

2022-03-14 08:33 UTC, karalabe commented on core/rawdb/key_length_iterator.go
> +// pairs where the key has length [keyLen].
If you want to refer to arguments by name in the docs, please use `` `arg` `` instead of the brackets. That would be more consistent with our code.

2022-03-14 08:34 UTC, karalabe requested changes
Nits, otherwise SGTM

2022-03-14 18:38 UTC, aaronbuchwald commented on core/rawdb/accessors_snapshot.go
> +	return NewKeyLengthIterator(db.NewIterator(storageSnapshotsKey(accountHash), nil), 65)
Updated

2022-03-14 18:39 UTC, aaronbuchwald commented
Made the requested changes, thanks for reviewing.

2022-03-15 07:49 UTC, rjl493456442 approved these changes

2022-03-15 08:27 UTC, karalabe approved these changes
LGTM

2022-03-15 08:28 UTC, merged