p2p: use errors.Is for error comparison
ethereum/go-ethereum pull request #24882
Opened 2022-05-15 18:01 UTC by estensen

I think from Go 1.13 on `errors.Is` is preferred for comparing errors.

One could argue that in some cases it's not necessary, like `!errors.Is(err, io.EOF)`, but hey, why not be consistent?

2022-05-16 12:05 UTC, holiman approved these changes
LGTM

2022-05-16 22:33 UTC, fjl commented
I kind of prefer `e == errXXX` in tests because it is stricter.

2022-05-17 09:15 UTC, fjl requested changes
Please revert changes in tests.

2022-05-18 01:58 UTC, Newman1515 requested changes
Request change

2022-06-07 09:57 UTC, holiman commented
Lots of odd errors, I rebased it now so hopefully that goes away

2022-06-07 15:27 UTC, merged