Signing raw transactions with a private key.
ethereum/go-ethereum pull request #25060
Opened 2022-06-10 14:51 UTC by gituser543

The ability to sign raw transactions with a private key, without importing the private key into the node.

2022-06-13 08:15 UTC, holiman requested changes
I'm opposed to having a public api endpoint accept private keys.

2022-06-13 08:15 UTC, closed without merging

2022-08-25 16:10 UTC, marcovelon commented
@holiman [holiman](https://github.com/holiman) please reconsider your decision. This is an important feature for projects that aggregate payments from different addresses and manage lots of private keys that are impractical to import to Geth.

This issue https://github.com/ethereum/go-ethereum/issues/16874 is a perfect example why this should be implemented. 

Considering that signing transaction without a Geth node would require using modules written in common languages such as NodeJS, Python or Go, for projects not written in those languages it's inconvenient to rewrite mechanisms such as RLP from scratch due to lack of module availability, given that consensus change quite often on Ethereum thus working module versions frequently become obsolete. A built-in possibility to do that in Geth will save a lot of time for many developers, since it has a constantly up-to-date consensus.

If your only concern is security, then it's recommended to make a startup flag to enable external private key signing feature, making it disabled by default.

2022-08-25 16:11 UTC, marcovelon commented
@holiman please reconsider your decision. This is an important feature for projects that aggregate payments from different addresses and manage lots of private keys that are impractical to import to Geth.

This issue https://github.com/ethereum/go-ethereum/issues/16874 is a perfect example why this should be implemented. 

Considering that signing transaction without a Geth node would require using modules written in common languages such as NodeJS, Python or Go, for projects not written in those languages it's inconvenient to rewrite mechanisms such as RLP from scratch due to lack of module availability, given that consensus change quite often on Ethereum thus working module versions frequently become obsolete. A built-in possibility to do that in Geth will save a lot of time for many developers, since it has a constantly up-to-date consensus.

If your only concern is security, then it's recommended to make a startup flag to enable external private key signing feature, making it disabled by default.

2022-08-25 16:22 UTC, holiman commented
If you have a key, and a raw transaction. Why do you have a need to ask a remote server to sign the one with the other ???

2022-08-25 16:38 UTC, marcovelon commented
> If you have a key, and a raw transaction.

We don't have a raw transaction and therefore use `eth_signTransaction` to create it. This PR actually permits doing it using an external key by passing `secretKey` parameter to `eth_signTransaction` and it's extremely practical. It's much better to use Geth for this instead of relying on some third-party modules that are often become obsolete.

2022-08-25 17:40 UTC, holiman commented
But why not use eth_fillTransaction, to obtain a raw tx, then sign locally , and submit the signed one via sendRawTransaction? 

2022-08-25 18:34 UTC, JurbinM approved these changes

2022-08-25 18:34 UTC, JurbinM approved these changes

2022-08-25 18:35 UTC, JurbinM approved these changes

2022-08-25 19:32 UTC, marcovelon commented
> But why not use eth_fillTransaction, to obtain a raw tx, then sign locally , and submit the signed one via sendRawTransaction? 

I have mentioned that already, but using third-party modules to sign ETH transactions can be very inconvenient, especially when a project is not written in a common language such as NodeJS, Python or Go and may lack an updated a web3 module, requiring us to rewrite a lot of things from scratch in order to implement `signTransaction`. 

Given that Geth and other cryptocurrency nodes operate in the same securely isolated LAN with our API, it's more convenient to offload things like transaction signing to the software that is already capable of doing so, instead of reinventing transaction signing mechanisms from scratch.

This commit is doing its job perfectly and definitely has use cases out there. We've been using it since @gituser543 submitted it and it never gave us a problem, even when we merged it with recent releases.

2022-08-26 07:48 UTC, holiman commented
>  have mentioned that already, but using third-party modules to sign ETH transactions can be very inconvenient, especially when a project is not written in a common language such as NodeJS, Python or Go and may lack an updated a web3 module,

Below is a golang snippet which takes a raw transaction and a raw private key, and signs the former with the latter. It's trivially simple, and using it will avoid _sending private keys over the network_, which is a fairly big no-no to me. 

I mean, it's still pretty dangerous, since you're handling private keys without encryption, and the private keys would show up in process listings, but at least the private keys are now contained in the machine and not broadcast over the network. 

```golang
package main

import (
	"fmt"
	"os"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: signer <private key hex> <raw tx rlp hex>")
	}
	pkey, err := crypto.HexToECDSA(os.Args[1])
	if err != nil {
		panic(err)
	}
	tx := new(types.Transaction)
	if err := tx.UnmarshalBinary(common.FromHex(os.Args[2])); err != nil {
		panic(err)
	}
	signedTx, err := types.SignTx(tx, types.LatestSignerForChainID(tx.ChainId()), pkey)
	if err != nil {
		panic(err)
	}
	output, _ := signedTx.MarshalBinary()
	fmt.Printf("%#x", output)
}
```
```
./signer 000000000000000000000000000000000000000000000000000000000000dead 01f8630103018261a894b94f5374fce5edbc8e2a8697c15331677e6ebf0b0a825544c001a0c9519f4f2b30335884581971573fadf60c6204f59a911df35ee8a540456b2660a032f1e8e2c5dd761f9e4f88f41c8310aeaba26a8bfcdacfedfa12ec3862d37521

0x01f8630103018261a894b94f5374fce5edbc8e2a8697c15331677e6ebf0b0a825544c001a07f034538f28f5842dfa45b059b98f57bd4196b2c7b75d8431ad994b04e2799efa03ff7bfe2ba112d007ba40c5f4d8c17889c36fb6c5236cd27fc7e4d569dd4f30f

```

2022-08-26 10:51 UTC, marcovelon commented
> So your code would, instead of making an http request, invoke a little executable signer which you build yourself.

Calling external executables with private keys in arguments is a far more dangerous practice than doing it via a HTTP API, any security expert will tell you that, because at least with HTTP API there are various ways to guarantee packet security by using encrypted transport layer and similar techniques. 

> I mean, it's still pretty dangerous, since you're handling private keys without encryption

Actually we handle private keys *with* encryption but you didn't want to hear that and simply ignore important points.

> I have, and it's still a "No."

Fine, it seems everything here depends only on your opinion then, I didn't know this and won't bother you anymore. Will seek for alternatives with more experienced maintainers.

2022-08-26 11:09 UTC, MariusVanDerWijden commented
Of course starting an executable with a private key is dangerous, I think @holiman's snippet should show how easy it is to implement a signer in go. You can read the private key from a file or from an encrypted keystore or use clef as an external signer. 

Our HTTP API is not secured and people will shoot themselves in the foot if we allow passing private keys via the api. 

> Fine, it seems everything here depends only on your opinion then, I didn't know this and won't bother you anymore. Will seek for alternatives with more experienced maintainers.

This is a bad idea and we will not implement it in geth.

2022-08-26 11:31 UTC, marcovelon commented
> Our HTTP API is not secured and people will shoot themselves in the foot if we allow passing private keys via the api.

That's why I have proposed the following previously: 

> make a startup flag to enable external private key signing feature, making it disabled by default.

However your stance on this is acknowledged and I disagree with it, thanks anyway.

2022-08-27 10:43 UTC, mostav02 commented
>> holiman: ...

Based on everything you wrote here, you have nearly zero understanding of tangible attack vectors, not even mentioning that you can barely read what's being written. No more surprised why Ethereum-related projects get hack after hack, since people like you are their best security advisors. You can't call yourself an appsec specialist yet, just because you wrote some beginner-level Java exploits and other JS nonsense that nobody from infosec professionals use.

Golang is already a security nightmare, but you make things even worse by forcing people to use it and turn their machines into botnet peers by downloading all those random 1000 github repos to compile a simple script. 

You should lower your speech here Martin, you are not what you think about yourself and still have much to learn. 

>> MariusVanDerWijden: This is a bad idea and we will not implement it in geth.

Just because you dislike something personally doesn't make it bad. What's really bad is you being unable to think on your own and automatically agreeing with some guy who talks nonsense and is barely competent in netsec. And yes, your friend really thinks appending private keys to executables ARGV is more secure than using an API. He meaned what he said and there is no need of trying to reinvent words meaning.

2022-08-27 10:47 UTC, mostav02 commented
>> holiman: ...

Based on everything you wrote here, you have nearly zero understanding of tangible attack vectors, not even mentioning that you can barely read what's being written. No more surprised why Ethereum-related projects get hack after hack, since people like you are their best security advisors. You can't call yourself an appsec specialist yet, just because you wrote some beginner-level Java exploits and other JS nonsense that nobody from infosec professionals use.

Golang is already a security nightmare, but you make things even worse by forcing people to use it and turn their machines into botnet peers by downloading all those random 1000 github repos to compile a simple script. 

You should lower your speech here Martin, you are not what you think about yourself and still have much to learn. 

>> MariusVanDerWijden: This is a bad idea and we will not implement it in geth.

Just because you dislike something personally doesn't make it bad. What's really bad is you being unable to think on your own and automatically agreeing with some guy who talks nonsense and is barely competent in netsec. And yes, your friend really thinks appending private keys to executables ARGV is more secure than using an API. He meaned what he said and there is no need of trying to reinvent words meaning.