cmd/devp2p: add eth cmd to send new block announcements
ethereum/go-ethereum pull request #25212
Opened 2022-06-30 15:27 UTC by lightclient

This PR adds a new subcommand to `devp2p`: `eth`. This subcommand has a single command of it's own currently, `new-block` which sends the specified hex as a devp2p block announcement message. We can expand `eth` to support more arbitrary message sending in the future.

```console
$ devp2p eth new-block <enode> <msg>
```

2022-08-09 03:37 UTC, lightclient commented
@fjl PTAL when you have a chance!

2022-08-10 16:34 UTC, lightclient commented on cmd/devp2p/ethcmd_test.go
> +func runGeth() (*node.Node, error) {
It's unfortunate this is mostly copied exactly from `cmd/devp2p/internal/ethtest/suite_test.go`. Not sure if there is anything better that could be done.

2023-02-15 10:05 UTC, holiman commented on cmd/devp2p/ethcmd.go
> +	}
@lightclient want to pursue this?

2023-03-07 19:29 UTC, holiman commented on cmd/devp2p/ethcmd.go
> +	}
..... ping ....

2023-03-14 20:20 UTC, fjl requested changes
The generic command is great, but a cli command with 3 args is not very ergonomic. We already have a command with 3 args, `devp2p rlpx eth-test`, and I could never remember the parameter order... It would be better to handle the args as flags. I suggest that it should be handled like this:

```
devp2p rlpx eth-msg -version 67 -node enr:... <code || msg>
```

i.e. only one positional argument and combined msg code + data.

2023-03-14 20:20 UTC, fjl commented on cmd/devp2p/ethcmd.go
> +		ProtocolVersion: 66,
This hard-coded version is going to be a problem. I think it should be passed as a flag.

2023-03-14 20:23 UTC, fjl commented
Another note: the original purpose of this command is kind of lost since the merge, because block announcements are not accepted via `eth` anymore. We could probably realize this test with the engine API now.

2023-03-14 21:00 UTC, lightclient commented
Yeah that is a good point, I'll see if I can update that hive PR to use the engine API instead.

2023-03-14 21:00 UTC, closed without merging