trie: improve node rlp-decoding
ethereum/go-ethereum pull request #25357
Opened 2022-07-21 02:58 UTC by rjl493456442

This PR improves node(mostly full node) rlp decoding efficiency by avoiding byte copy.

Currently, bytes will be deep copied from the given byte stream to node struct when decoding. If we can hold the assumption that the provided byte stream is immutable, then we can avoid this deep copy.

It turns out this optimization can decrease the time from 1000ns to 670ns on my laptop for decoding a full node, 33% speedup.

2022-08-11 08:53 UTC, fjl requested changes
Please add a copy of `result.Data` here:

https://github.com/ethereum/go-ethereum/blob/a9ef135e2dd53682d106c6a2aede9187026cc1de/trie/sync.go#L302-L304

Reason: the input bytes in this invocation of `decodeNode` are passed into the trie sync code from p2p, and we cannot be certain whether the input slice will be reused.

2022-08-15 06:48 UTC, rjl493456442 commented
@fjl I have updated the PR. 

Now we have two version decoders: `decodeNode` and `decodeNodeUnsafe`, the only difference between them is `decodeNode` will deep-copy the input and then decode the node, namely one additional allocation.

`decodeNodeUnsafe` is only used in `trie.Database`, (a) the blob resolved from clean cache (b) the blob resolved from database (c) the blob resolved either from clean cache or database, which I believe is safe to decode without deep-copy.

The good news is that even for the sub-optimal version `decodeNode`, it's still much better than the original version. The difference comes from the number of allocations. For example. previously, there are multiple allocations applied for deep-copy each children, now only the single deep-copy is required(applied on the input).

Please take a look.

2022-08-18 12:06 UTC, holiman approved these changes
This looks good to me

2022-08-18 22:35 UTC, fjl approved these changes

2022-08-18 22:39 UTC, merged