accounts/abi: fix set function
ethereum/go-ethereum pull request #25477
Opened 2022-08-04 12:50 UTC by zhiqiangxu

Without this patch, this test will report `abi: cannot unmarshal string in to string`:

https://github.com/zhiqiangxu/multicall/blob/master/multicall_test.go#L96

After this patch, the above test will pass.

After all, there's no point to call `set` on `dst.Elem()` if `dst.Elem()` can not be set (`CanSet` returns `false`)

2022-08-04 15:43 UTC, gballet requested changes
Could you please:

 * [x] Fix the geth test that this PR breaks
 * [ ] Add a _simpler_ test into this PR that reproduces the issue. The test you provided belongs to a different repository, and does way more things than needed to reproduce the issue.

2022-08-04 16:22 UTC, zhiqiangxu commented
> 

Done. Basically now you can unpack a solidity string into both `[]interface{""}` or `[]interface{new(string)}`, previously you can only unpack it into `[]interface{new(string)}`.

2022-08-04 16:23 UTC, zhiqiangxu commented
> Could you please:
> 
> * [ ]  Fix the geth test that this PR breaks
> * [ ]  Add a _simpler_ test into this PR that reproduces the issue. The test you provided belongs to a different repository, and does way more things than needed to reproduce the issue.

Done. Basically now you can unpack a solidity string into both []interface{""} or []interface{new(string)}, previously you can only unpack it into []interface{new(string)}.

2022-08-18 11:31 UTC, holiman approved these changes
LGTM

2022-08-18 11:32 UTC, holiman commented
@gballet lgty ?

2022-08-19 10:15 UTC, merged