miner: build a more Merge friendly pending block
ethereum/go-ethereum pull request #25835
Opened 2022-09-21 00:30 UTC by riposteX

Adjust geth's block building parameters to produce (most of the time) a block acceptable to consensus clients.

* Set header.Time = parent.Time() + 12. This is the correct value unless the previous slot block proposal was missed.

* Set header.MixDigest = parent.Header().MixDigest. This is the correct value except at the beginning of a new epoch.

* Apply FinalizeAndAssemble to the snapshot block. This sets header.Root

An alternative would be to add/modify an API which allows the user to specify these values, similar to how the consensus client currently acquires a block from geth.

2022-09-22 11:47 UTC, riposteX commented
Oops - saw that randao_mixes was a vector indexed by epoch, but didn't think to question the mix part of that label. Apparently this gets modified every slot, so we can't just use the previous block's header.MixDigest.

I'd really like to be able to extract a valid pending block from Geth. It seems rather unwise to try and use the engine API, as FCU interactions could interfere with the consensus client operations.

What do you think about allowing an empty `update.HeadBlockHash` in `ForkchoiceUpdatedV1`? The function comments indicate that this should return success, but it currently returns an error. What if we allow an empty head to skip all the blockchain updating logic and just return a payoadId?

That way anyone could use the engine API to extract a block without worrying about interfering with the consensus client.

2022-09-22 12:03 UTC, riposteX commented
Still think these changes are worth doing, however, as they make the pending block more like the real one that gets produced through the engine API.

2022-09-26 06:27 UTC, rjl493456442 requested changes
I don't think we will accept this change.

Firstly in the legacy block building procedure, Geth will re-generate sealing block every 3 seconds in the same round, with the same timestamp. It's necessary and doesn't need to be updated every time(otherwise will lead to a smaller block difficulty).

Secondly, ethereum has switched to Proof-of-Stake mechanism and we will retire this part of block building logic. We don't want to accept more changes.

2022-09-26 06:29 UTC, rjl493456442 commented
Sorry I will close the PR, thanks for your contribution though.

2022-09-26 06:29 UTC, closed without merging