docs: add page on log messages
ethereum/go-ethereum pull request #25930
Opened 2022-10-05 09:41 UTC by jmcook1186

Attempting to create a page that helps users interpret common console logs. In particular addresses:

1) how to configure logs - i.e. verbosity and redirecting to file
2) startup logs (for default config)
3) syncing logs (for default snap sync)
4) transaction logs (for simple eth transfer)
5) explaining commonly-queried logs 

Raising as a draft PR for now to see if Geth team have suggestions for messages that are commonly asked about by users or other important log messages I've overlooked.

2022-10-20 19:50 UTC, lightclient reviewed
Looks pretty good to me overall. Might also be nice to have a section discussing the output of `eth_syncing` if it doesn't already exist.

2022-10-20 19:50 UTC, lightclient commented on docs/_interface/logs.md
> +usually sufficiently self-descrining that they do not require additional explanation.
```suggestion
usually sufficiently self-describing that they do not require additional explanation.
```

2022-11-04 07:52 UTC, s1na requested changes
This is great! only a few nits:

2022-11-04 07:52 UTC, s1na commented on docs/_interface/logs.md
> +For state sync, Geth reports when the state heal is in progress. This can takea long time.
```suggestion
For state sync, Geth reports when the state heal is in progress. This can take a long time. 
```

2022-11-04 07:52 UTC, s1na commented on docs/_interface/logs.md
> +INFO [07-28|10:30:21.665] Imported new state entries
The "Imported new state entries" log is incomplete, missing the arguments.

2022-11-04 07:52 UTC, s1na commented on docs/_interface/logs.md
> +```json
```suggestion
```console
```

With JSON type it shows red rectangles around all the words because it's invalid JSON

2022-11-04 07:52 UTC, s1na commented on docs/_interface/logs.md
> +[consensus clients](/docs/interface/consensus-clients.md) page.
Link doesn't work

2022-11-04 10:05 UTC, jmcook1186 commented on docs/_interface/logs.md
> +```json
```suggestion
```js
```
for consistency with other snippets

2022-11-04 21:17 UTC, holiman requested changes

2022-11-04 21:17 UTC, holiman commented on docs/_interface/logs.md
> +INFO [07-28|10:30:21.665] Imported new state entries
```suggestion
```

2022-11-04 21:17 UTC, holiman commented on docs/_interface/logs.md
> +[consensus clients](/docs/interface/consensus-clients.md) page.
```suggestion
[consensus clients](/docs/interface/consensus-clients) page.
```

2022-11-04 21:17 UTC, merged