cmd/clef: add importraw feature to clef
ethereum/go-ethereum pull request #26058
Opened 2022-10-28 12:08 UTC by holiman

This adds `importraw` as a subcommand to clef. 

Walking the happy-path:
```
[user@work clef]$ go run . --suppress-bootwarn importraw ./hexkey
INFO [10-28|14:03:08.718] Starting clef                            keystore=/home/user/.ethereum/keystore light-kdf=false
DEBUG[10-28|14:03:08.719] FS scan times                            list="61.22µs" set="72.06µs" diff="6.886µs"
## Password

Please enter a password for the imported account
> 
-----------------------
## Password

Please repeat the password you just entered
> 
-----------------------
DEBUG[10-28|14:03:15.040] FS scan times                            list="78.702µs" set="74.598µs" diff="6.765µs"
## Info 
Key imported:
  Address 0x9160DC9105f7De5dC5E7f3d97ef11DA47269BdA6
  Keystore file: /home/user/.ethereum/keystore/UTC--2022-10-28T12-03-13.976383602Z--9160dc9105f7de5dc5e7f3d97ef11da47269bda6

The key is now encrypted; losing the password will result in permanently losing 
access to the key and all associated funds!

Make sure to backup keystore and passwords in a safe location.

```

2022-11-01 13:36 UTC, fjl requested changes

2022-11-01 13:36 UTC, fjl commented on cmd/clef/main.go
> +	}
Please use `crypto.LoadECDSA` here.

2022-11-02 18:24 UTC, holiman commented
This PR now also adds `clef` CLI tests, covering the `importraw`, `list-accounts` and `list-wallets` commands. cc @jmcook1186

2022-11-02 18:33 UTC, holiman commented on cmd/clef/run_test.go
> +// runClef spawns geth with the given command line args and adds keystore arg.
```suggestion
// runClef spawns clef with the given command line args and adds keystore arg.
```

2022-11-02 18:34 UTC, holiman commented on cmd/clef/run_test.go
> +// runClef spawns geth with the given command line args and adds keystore arg.
```suggestion
// runClef spawns clef with the given command line args and adds keystore arg.
```

2022-11-02 18:34 UTC, holiman commented on cmd/clef/run_test.go
> +	// Run the app if we've been exec'd as "geth-test" in runGeth.
```suggestion
```

2022-11-02 18:35 UTC, holiman commented on cmd/clef/run_test.go
> +// runClef spawns clef with the given command line args and adds keystore arg.
```suggestion
// runWithKeystore spawns clef with the given command line args and adds keystore arg.
```

2022-11-02 18:35 UTC, holiman commented on cmd/clef/consolecmd_test.go
> +// TestListAccounts tests clef --list-wallets
```suggestion
// TestListWallets tests clef --list-wallets
```

2022-11-06 12:02 UTC, fjl approved these changes

2022-11-06 12:02 UTC, merged