[website] refactor(components): trim syntax for icons, svgs.
ethereum/go-ethereum pull request #27130
Opened 2023-04-20 19:03 UTC by TylerAPfledderer

_Updated version of #26739. cc @corwintines for primary approval and merging by request_

Trims the syntax for all of the svgs under `components/icons` and `components/svgs`.

## Current Rendering
The icons currently render a nested `svg` due to this element being added in the `path` prop, but `createIcon` renders the element.

## New Rendering
- Nested svgs are removed from `path` prop
- Single paths are moved to the `d` prop. `fill='currentColor'` here is rendered by default.
- For some of the icons, `width` and `height` are removed because of implementation where only the `viewBox` is needed
  - By default, the icons are rendered with `width: '1em'` and `height: '1em`'  so that `fontSize` can also be used.
- The `defaultProps` prop is used for when the width, height, color, or `fill: 'none'` need to be supplied to the svg (and removes the  added level of abstraction in exporting a layered `Icon` component!)

2023-04-21 19:21 UTC, corwintines requested changes
Found one issue, but everything else looks good here.

2023-04-21 19:21 UTC, corwintines commented on src/components/UI/svgs/GopherHomeNodes.tsx
@TylerAPfledderer I think there was a mistake here. Looks like the paths match up with `GopherHomeLinks`. As well as the naming changed from `GopherHomeNodes` to `GopherHomeLinks` here too.

2023-04-22 23:41 UTC, TylerAPfledderer commented on src/components/UI/svgs/GopherHomeNodes.tsx
@corwintines ahh indeed! 😅

2023-04-22 23:42 UTC, TylerAPfledderer commented
@corwintines change made for the svg in question, and also fixed `GlyphHome` where a fill was being applied when it should be `fill: none`

2023-05-03 15:33 UTC, corwintines approved these changes

2023-05-03 15:33 UTC, merged