accounts/abi: add ErrorById
ethereum/go-ethereum pull request #27277
Opened 2023-05-16 07:52 UTC by chawin-a

### Changes
- Modify ID type from `common.Hash` to `[]byte` in Error struct
- Add ErrorById

2023-05-16 08:38 UTC, fjl commented on accounts/abi/abi.go
> +		if bytes.Equal(errABI.ID, sigdata[:4]) {
I wonder why you changed the `ID` field to `[]byte`. Might be better to:

- change the type of the `sigdata` parameter to `[4]byte`
- do the check like bytes.Equal(errABI.ID[:4], sigdata[:])`

2023-05-16 12:21 UTC, deep709 commented
Thanks all

2023-05-17 09:07 UTC, fjl commented
Please apply the requested changes!

2023-05-17 09:40 UTC, chawin-a commented
Done please review the changes

2023-05-17 21:39 UTC, fjl requested changes
Sorry some more changes needed

2023-05-17 21:39 UTC, fjl commented on accounts/abi/error.go
> +	ID [4]byte
You don't need to change the `ID` to make the function `ErrorByID` work.

2023-05-17 21:39 UTC, fjl commented on accounts/abi/abi.go
> +func (abi *ABI) ErrorById(sigdata [4]byte) (*Error, error) {
Please rename this method to `ErrorByID`

2023-05-18 04:26 UTC, chawin-a commented
Please review the changes again.

2023-05-22 14:23 UTC, MariusVanDerWijden approved these changes
LGTM

2023-05-22 16:45 UTC, merged