impr(vm): Use golang built-ins for `PUSHX` opcode
ethereum/go-ethereum pull request #29515
Opened 2024-04-12 05:29 UTC by itsdevbear

2024-04-12 05:36 UTC, holiman requested changes
The changes to `makePush` are fine, but I don't see why you made changes to `opPush1`?

2024-04-12 05:43 UTC, itsdevbear commented
@holiman reverted, though could reduce the lines of code on push1 if we want, integer and codeLen only used once.

2024-04-16 10:11 UTC, holiman approved these changes
LGTM

2024-04-16 12:55 UTC, karalabe commented on core/vm/instructions.go
> +			end     = min(start+pushByteSize, codeLen)
Could you flip the args to keep it consistent with the old code (and the pre min invocation?)

2024-04-16 12:57 UTC, karalabe approved these changes
LGTM

2024-04-16 12:57 UTC, merged