accounts/abi/bind: keep test file package name consistent
ethereum/go-ethereum pull request #29816
Opened 2024-05-22 03:26 UTC by hattizai

This PR adds some small code cleanup:
- accounts/abi/bind: keep test file package name consistent
- common: sort variables to make code more clear
- core: remove redundant type declaration

2024-05-22 03:54 UTC, sara554-beep requested changes
Nose utilizar la aplicación ni como poder hacer cambios

2024-05-22 07:55 UTC, hattizai commented
> Nose utilizar la aplicación ni como poder hacer cambios

Please stop your spam

2024-05-23 02:37 UTC, rjl493456442 approved these changes
Yeah, it's indeed inconsistent.

Although, normally we use the same package name for tests, but I think it should be fine to use `bind_test` here. Using `bind` for tests could result in a larger diff then.

2024-05-23 02:44 UTC, AaronChen0 commented
There are many cases like this, if you run
```
find . -name "*test.go" | xargs grep '^package'
```

2024-05-23 03:15 UTC, hattizai commented
> There are many cases like this, if you run
> 
> ```
> find . -name "*test.go" | xargs grep '^package'
> ```

@AaronChen0 I'm sorry, but the output of the script is a mess, did you mean that all the test file in the output has the same issue? Could you please check the script again?

2024-05-23 03:35 UTC, AaronChen0 commented
Your idea is to put the tests into a separate test package, right?
But most `*test.go` files have this `inconsistency`. Should we change them all?
A grep command with color output
```
grep --include=*test.go -R '^package'
```

2024-05-23 03:57 UTC, hattizai commented
Nope, I think it's ok to just keep the test file package consistent under the same folder, no matter `{package}` or `{package_test}`

I did some statistics just now, all the folders that contain inconsistent test package names are the following:
- accounts/abi/bind
- common/hexutil/
- core/types/
- core/vm/runtime/
- event/
- node/
- rlp/
- rpc/
- signer/core

This touches a lot of packages, maybe I should split it into multiple PRs.

@rjl493456442 Sir, what do you think of this? Shall we rename all `{package_test}` to `{package}` or just depends on the diff changes of `{package_test} => {package}` and `{package} => {package_test}`

2024-05-23 09:01 UTC, closed without merging