beacon/light: handle endpoint URL more gracefully
ethereum/go-ethereum pull request #30306
Opened 2024-08-15 15:11 UTC by s1na

blsync was failing if the light endpoint it was provided ended with a `/`. This change should handle the joining more gracefully.

2024-08-15 15:17 UTC, lightclient approved these changes

2024-08-15 15:34 UTC, fjl approved these changes

2024-08-15 16:24 UTC, s1na commented
Ah it seems like url.JoinPath is escaping the `?` which is there for the parameters.

2024-08-15 16:34 UTC, lightclient commented
Hmm right, it looks like `URL.String()` does the escaping.

2024-08-15 16:34 UTC, lightclient requested changes
dismissing review

2024-08-15 16:54 UTC, s1na commented
Should be fixed now

2024-08-16 12:39 UTC, merged

2024-09-11 20:25 UTC, zsfelfoldi commented
> Should be fixed now. I know I could have just trimmed the slash at the end of the base URL but isn't this cooler? :))

Yeah, apparently so cool that no one bothered to check whether the thing actually still works :)