core/txpool/blobpool: avoid possible zero index panic
ethereum/go-ethereum pull request #30430
Opened 2024-09-13 14:51 UTC by mask-pp

This situation(`len(txs) == 0`) rarely occurs, but if it does, it will panic.

2024-09-13 17:55 UTC, holiman requested changes
One minor nit, otherwise this looks like a correct fix to me!

2024-09-13 17:55 UTC, holiman commented on core/txpool/blobpool/blobpool.go
> +		for ; len(txs) > 0 && txs[0].nonce < next; txs = txs[1:] {
```suggestion
		for len(txs) > 0 && txs[0].nonce < next {
```
Please move the `txs = txs[1:]` back below, the code was easier to read that way.

2024-09-14 06:43 UTC, namiloh commented on core/txpool/blobpool/blobpool.go
> -			txs = txs[1:]
Don't forget to add this back

2024-09-14 13:45 UTC, holiman approved these changes
Thanks!

2024-09-14 13:45 UTC, merged

2024-09-20 03:25 UTC, minh-bq commented
In my opinion, it's impossible to cause the panic. The panic only happens when all transactions in `txs` has nonce lower than `next`. But if that is the case, it will fall into `filled` case above this logic and the function returns. Do I miss anything?

2024-09-20 06:30 UTC, holiman commented
> In my opinion, it's impossible to cause the panic.

I would suspect you are correct, but I didn't spend a lot of time investigating. The thing is, with the change in this PR, it is trivial to ascertain that code is correct and will not `panic`. Without it, one has to analyze the preconditions that lead up to a potential crash. 

So, code is clearer and more robust with this PR (more robust since any changes in events leading up to the vulnerable line can no longer cause the bug to trigger).