remove useless `SetZero`
ethereum/go-ethereum pull request #30472
Opened 2024-09-20 02:55 UTC by zhiqiangxu

The default value of `fr.Element` is already zero, you can see the evidence in `go-verkle` here:

1. https://github.com/ethereum/go-verkle/blob/dffa7562dbe971a9776f43795d49177a18ecb5c8/tree.go#L273

2. https://github.com/ethereum/go-verkle/blob/dffa7562dbe971a9776f43795d49177a18ecb5c8/tree.go#L294

2024-09-20 06:34 UTC, jwasinger approved these changes

2024-09-20 07:28 UTC, gballet requested changes
probably fine, but I'm blocking this until I was able to check on a testnet

2024-11-08 14:27 UTC, holiman approved these changes
LGTM

2024-11-08 14:27 UTC, holiman commented
> probably fine, but I'm blocking this until I was able to check on a testnet

Nah, there is nothing to check. It is how go works.

2024-11-08 14:28 UTC, merged