core/state/snapshot: simplify snapshot rebuild
ethereum/go-ethereum pull request #30772
Opened 2024-11-20 16:03 UTC by ARR4N

This PR is purely for improved readability; I was doing work involving the file and think this may help others who are trying to understand what's going on.

1. `snapshot.Tree.Rebuild()` now returns a function that blocks until regeneration is complete, allowing `Tree.waitBuild()` to be removed entirely as all it did was search for the `done` channel behind this new function.
2. Its usage inside `New()` is also simplified by (a) only waiting if `!AsyncBuild`; and (b) avoiding the double negative of `if !NoBuild`.

2024-11-20 18:25 UTC, Mahmoudhpp approved these changes

2024-11-21 11:57 UTC, holiman approved these changes
Very elegant, looks good to me!

2024-11-21 11:59 UTC, holiman commented
Seems to get stuck though :) 
```
goroutine 22 [runnable]:
github.com/ethereum/go-ethereum/core/state/snapshot.New({0xc0003be008?, 0x2?, 0x0?, 0x0?}, {0x7f52d24be8f8, 0xc00003a680}, 0xc00045e030, {0xec, 0xec, 0xdf, ...})
	/home/appveyor/projects/go-ethereum/core/state/snapshot/snapshot.go:222 +0x2b2
github.com/ethereum/go-ethereum/core.NewBlockChain({0xac60f0, 0xc00003a680}, 0x0?, 0xc00003fe48, 0x0, {0xac3cb0, 0xc0001006c0}, {0x0, 0x0, 0x0, ...}, ...)
	/home/appveyor/projects/go-ethereum/core/blockchain.go:449 +0x182a
github.com/ethereum/go-ethereum/consensus/clique.TestReimportMirroredState(0xc00015b520)
```

2024-11-21 12:01 UTC, holiman requested changes

2024-11-21 12:01 UTC, holiman commented on core/state/snapshot/snapshot.go
>  	}
You turned this into an endless loop, I think

2024-11-21 13:32 UTC, ARR4N commented
> Seems to get stuck though :)

Whoops, I read the `for head != nil` as `if head != nil`. Thanks for reverting that.

2024-11-21 17:16 UTC, ARR4N commented
@holiman sorry for the [post-approval push](https://github.com/ethereum/go-ethereum/pull/30772/commits/f86318ca1a5b74df19fc79406c79a068176c4545). I just made the for loop obvious as I and another developer I spoke to both assumed it was an `if` statement.

2024-11-22 03:34 UTC, rjl493456442 commented
Personally I don't think it's worthwhile to include the changes, as this structure will be soon merged into pathdb.

2024-11-22 08:10 UTC, holiman commented
> Personally I don't think it's worthwhile to include the changes, as this structure will be soon merged into pathdb.

You have a point... However, it doesn't seem to be touched by the upcoming parts 2-5 of snapshot integration?

2024-11-25 12:43 UTC, merged