Add Tests for Debug Tracing Methods
ethereum/go-ethereum pull request #30911
Opened 2024-12-13 19:01 UTC by sina-haseli

This PR addresses **[Issue #30833](#30833)**, which highlights the need for improved test coverage for debug tracing methods in the project.

### Changes
The following methods now have tests to ensure their reliability and functionality:

* `debug_standardTraceBlockToFile`
* `debug_standardTraceBadBlockToFile`
* `debug_intermediateRoots`
* `debug_traceBadBlock`

These tests have been added to the `eth/tracers/api_test.go file`.

### Purpose
These methods are crucial for debugging and diagnosing issues when something goes wrong. Expanding test coverage will help ensure they are ready for use in critical situations.

### Notes
This contribution is aimed at improving the tracing API’s reliability. Feedback is welcome to:

- Suggest improvements for the tests.
- Guide further contributions to the project.

If these changes align with the project’s goals, I’d be happy to continue contributing!

2024-12-16 11:16 UTC, s1na requested changes
Hey thanks for this. I have requested some changes please take a look.

2024-12-16 11:16 UTC, s1na commented on eth/tracers/api_test.go
> +	_ = os.WriteFile(name, data, 0644)
Let's use testing's TempDir to put the files in so the working directory is not polluted. https://pkg.go.dev/testing#F.TempDir

2024-12-16 11:16 UTC, s1na commented on eth/tracers/api_test.go
> +		panic(fmt.Errorf("failed to encode block: %v", err))
Either return the error and use `t.Fatalf` or pass `t` to the function so you can do it here.

2024-12-16 11:16 UTC, s1na commented on eth/tracers/api_test.go
> +	backend := newTestBackend(nil, genBlock, genesis, func(i int, b *core.BlockGen) {
This is a good start but the blocks will have empty traces. It will be great if some code is executed too as part of a tx in there.

2024-12-16 11:16 UTC, s1na commented on eth/tracers/api_test.go
> +	backend := newTestBackend(t, 2, genesis, func(i int, b *core.BlockGen) {
Specifically when it comes to intermediate roots it would be good to modify the state apart from only the transfer. e.g. some SSTORE as part of a tx.

2024-12-16 11:16 UTC, s1na commented on eth/tracers/api_test.go
> +				if len(roots) == 0 {
Right this is not enough we need to actually check the root hashes.

2024-12-16 20:36 UTC, sina-haseli commented
@s1na  Thanks for the feedback! 😊 I've made all the changes you suggested. Whenever you get a chance, please take another look and let me know if everything’s good now.

2024-12-27 23:33 UTC, sina-haseli commented
Hey @ s1na, is there anything wrong with these changes, or how long does it take to review or accept this pull request?

2025-01-03 15:19 UTC, s1na commented on eth/tracers/api_test.go
> +			expected: fmt.Sprintf(`{"txHash":"%s","result":{"gas":21068,"failed":false,"returnValue":"","structLogs":[]}}`, backend.chain.GetBlockByNumber(backend.chain.CurrentBlock().Number.Uint64()).Transac
This doesn't look right. The `structLogs` field should be non-empty.

2025-01-03 17:12 UTC, s1na commented
Hey @sina-haseli pardon for the delay. I got a chance now to check your PR and left some comments. Please leave out the test for tracing bad blocks to another PR. Let's just do TraceBlock and TraceIntermediateRoots in this one.

2025-05-05 21:00 UTC, lightclient commented
Author has not responded to feedback in about 5 months, going to close for now. Please reopen if you decide to pick this up!

2025-05-05 21:00 UTC, closed without merging